### ISSUE TITLE
302 and 307 redirects behaving differently

### ISSUE THREAD

**Issue by valtlai** [aaronpk/indielogin.com#100]
My site had a **307** redirect from `/` to `/en/` (or `/fi/` depending on the Accept-Language request header), which caused the following message to appear when trying to sign in with `https://valtlai.fi`:

<img width="650" height="98" alt="Your GitHub profile linked to https://valtlai.fi/ but we were expecting to see https://valtlai.fi/en/. Make sure you link to https://valtlai.fi/en/ in your GitHub profile." src="https://user-images.githubusercontent.com/5496284/220964380-0cfc2072-089b-44ee-b0d4-5f1ed8c72acb.png">

After changing the status code to **302**, I was able to sign in again:

<img width="500" height="160" alt="Congrats! You successfully authenticated as https://valtlai.fi/." src="https://user-images.githubusercontent.com/5496284/220966910-7288add0-8b09-489b-83dc-11e3db577112.png">

Is it intentional that the mostly equivalent HTTP status codes (302 Found, 307 Temporary Redirect) are behaving differently on IndieLogin.com? Can this be fixed?

**Comment by aaronpk** [comment]
No this was not intentional. I'm pushing a fix that treats 302 and 307 the same. Thanks.
