### ISSUE TITLE
Error: Your IndieAuth server did not return a valid state parameter

### ISSUE THREAD

**Issue by vikanezrimaya** [aaronpk/indielogin.com#106]
- indielogin.com login flow init page URL: `https://indielogin.com/auth?client_id=https%3A%2F%2Findieweb.org%2F&redirect_uri=https%3A%2F%2Fsso.indieweb.org%2Fauth&response_type=code&state=FQ0%2B6yDL8YE6TG9ZANhS%2BksGvKzxPFTaVLJ%2Fo0Rdq2s%3D`
 - The request to the authorization endpoint: `https://fireburn.ru/.kittybox/indieauth/auth?response_type=code&me=https%3A%2F%2Ffireburn.ru%2F&redirect_uri=https%3A%2F%2Findielogin.com%2Fredirect%2Findieauth&client_id=https%3A%2F%2Findielogin.com%2F&state=f0aa4cb22cd44a124adf24c2&code_challenge=gXCTMMp80e3J11Edsri9cZHiYaVh5gdRbh9uLQSu_78&code_challenge_method=S256`
 - Request data as parsed by Kittybox:
   | Key | Value |
   |--------|--------|
   | Response type | `code` |
   | Request state | `f0aa4cb22cd44a124adf24c2` |
   | Client ID | `https://indielogin.com/` |
   | Redirect URI | `https://indielogin.com/redirect/indieauth` |
   | PKCE code challenge | `gXCTMMp80e3J11Edsri9cZHiYaVh5gdRbh9uLQSu_78` |
   | PKCE method | `S256` |
 - Final redirect link: `https://indielogin.com/redirect/indieauth?code=6Ep0IiFlrXhEk4fe&state=f0aa4cb22cd44a124adf24c2&iss=https%3A%2F%2Ffireburn.ru%2F`
 - Error message: see title

**Comment by aaronpk** [comment]
Do you have any browser extensions that block cookies or anything?

**Comment by vikanezrimaya** [comment]
Oh, apparently disabling tracking protection has done something. Solved.
