### ISSUE TITLE
"The session expired"

### ISSUE THREAD

**Issue by jphastings** [aaronpk/indielogin.com#108]
Hi folks, I'm getting a "The session expired" every time I try to authenticate with PGP.

(This is the same issue mentioned by a number of people [posting on an unrelated issue](https://github.com/aaronpk/indielogin.com/issues/66), so I figured I'd break it out into its own issue.)

My reproducing actions are:
1. Visit IndieLogin.com and enter my domain
2. Select the string to be signed with PGP and use [GPG Suite](https://gpgtools.org/)'s "services" for mac os to sign in-place
    <img width="1276" alt="Screenshot 2023-07-25 at 21 20 19" src="https://github.com/aaronpk/indielogin.com/assets/42999/468c2908-d32b-49c7-89a4-f25ad0f22bca">
3. I receive a message: "The session expired"
     <img width="397" alt="Screenshot 2023-07-25 at 21 23 38" src="https://github.com/aaronpk/indielogin.com/assets/42999/02563f8f-1f09-461f-add0-8d1631ae7e6d">

I'm certain it's not an issue with this signing method, as it functions perfectly on indieauth.com. Can you help?

**Comment by aaronpk** [comment]
hmm, you don't have any browser extensions that might be blocking cookies do you?

**Comment by jphastings** [comment]
It's definitely possible (I'm using [Arc](https://arc.net/) — I've since set my site to use indieauth.com instead, so I'm no longer easily able to test this, but I'll swap back and see whether it's still exhibiting in a more relaxed browser!

**Comment by aaronpk** [comment]
I'm not sure how you were able to set your site to use this, since it is not the same kind of identity provider as indieauth.com is. You should only end up at indielogin.com from a website that uses it to sign users in, like indieweb.org.
