### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/indielogin.com#12]
I try to sign in to telegraph.p3k.io (which now uses indielogin.com) and it presents the following error:

`Your IndieAuth server did not return a valid response. Below is the response from your server.`
```
{
    "error": "Not found"
}
```

The issue might be with my IndieAuth server, but the strange thing is it works fine for logging into Monocle and Aperture.

**Comment by aaronpk** [comment]
Monocle and Aperture get access tokens from your site, so they talk to your token endpoint when logging in. IndieLogin.com just verifies auth codes, so it's making a post request to your authorization endpoint, which is where it's getting this error from. I'm guessing your authorization endpoint isn't set up to handle post requests.

**Comment by EdwardHinkle** [comment]
This has been fixed. The authentication code was sending data as multi-part. It’s now url encoded.
