### ISSUE TITLE
Capital letters in account names not recognized

### ISSUE THREAD

**Issue by MegaByte** [aaronpk/indielogin.com#13]
When I first tried to login using GitHub, indielogin complained that there was a username mismatch -- I had specified "megabyte" in the URL, but GitHub had passed "MegaByte" Same deal with Twitter.

I then changed the URLs on my site to use capitals, but now indielogin complains "None of the rel=me URLs found on your page were recognized as a supported provider" Both GitHub and Twitter should work, but they both use capital letters in the username and so are ignored.

**Comment by MegaByte** [comment]
Also, GitHub allows hyphens in usernames as long as they don't start or end the username and do not appear in succession. It does not allow underscores.

**Comment by martymcguire** [comment]
I also ran into this recently with a Twitter account @CryptoPartyBalt.

Discussion: https://chat.indieweb.org/dev/2018-07-11#t1531334552107000
