### ISSUE TITLE
Checking against GitHub linked website fails due to lack of trailing slash.

### ISSUE THREAD

**Issue by davmillar** [aaronpk/indielogin.com#16]
I tried deferring to GitHub for my login experience, but it failed due to IndieLogin appending a trailing slash that isn’t present on the link in my GitHub profile.

![946bcd6f-12ef-404f-b23b-2e0c7fafa954](https://user-images.githubusercontent.com/576958/46179470-08dbea80-c281-11e8-9d2d-e250e722d398.jpeg)

**Comment by vmx** [comment]
I got the same issue even with a slash. My error message is:

> Your GitHub profile linked to https://vmx.cx/ but we were expecting to see https://vmx.cx/. Make sure you link to https://vmx.cx/ in your GitHub profile.

**Comment by Lewiscowles1986** [comment]
Up to you both, but surely updating your GitHub website URL might be easier and faster?

**Comment by aaronpk** [comment]
I can't seem to replicate this. Can you try it again? I think this may have been fixed already.

**Comment by aaronpk** [comment]
I'm going to close this since I haven't been able to replicate it and it has likely been fixed in the mean time. Please let me know if it continues to be a problem.

**Comment by vmx** [comment]
I can login with GitHub now and I don't think I've changed anything, so it really seems to be fixed. Thanks.
