### ISSUE TITLE
Twitter and redirects

### ISSUE THREAD

**Issue by vmx** [aaronpk/indielogin.com#17]
The homepage of my website is a redirect. Something is returning the redirected page and not the original link in my profile. My profile has `https://vmx.cx/` in there, but I get this error message:

> Your Twitter profile linked to https://vmx.cx/cgi-bin/blog/index.cgi but we were expecting to see https://vmx.cx/. Make sure you link to https://vmx.cx/ in your Twitter profile.

Which indicates that it was following the redirect.

**Comment by jalcine** [comment]
This is according to the specification of IndieAuth though, https://indieauth.spec.indieweb.org/#redirect-examples

**Comment by aaronpk** [comment]
This actually doesn't involve the IndieAuth spec at this point, although there are some similarities.

I thought the thing you're trying to do should be supported, so I'm going to have to walk through this again. Specifically, there is some code that deals with permanent (301) vs temporary (302) redirects from the link in your Twitter bio which should have been taking this into account.

**Comment by vmx** [comment]
@jalcine I have do admit I haven't read the full spec. But I've read the part about redirects. Let's see if I understand that correctly. I have a temporary redirect (302) from `https://vmx.cx/` to `https://vmx.cx/cgi-bin/blog/index.cgi`. So the profile URL should be `https://vmx.cx/` and the authorization endpoint should be `https://vmx.cx/cgi-bin/blog/index.cgi` which I think is the case.

@aaronpk Thanks, your comment was just popping up as I was already almost done writing the top-part, so I thought I leave it in.
