### ISSUE TITLE
Verifying the authorization code with IndieLogin.com failed

### ISSUE THREAD

**Issue by sreenivaska** [aaronpk/indielogin.com#18]
When we make Ajax POST call from javascript to 
URL : https://indielogin.com/auth with the following parameters 
code=gk7n4opsyuUxhvF4&
redirect_uri=https://example.com/callback&
client_id=https://example.com/

We are getting 400 Status code.
Here is the error 
XMLHttpRequest cannot load https://indielogin.com/auth?code=bd5890f132614077cb99e22aed8f641f92f5890cb6…egistration-page/indie_auth_returnurl.html&client_id=https://example.com. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.

Please suggest on how to handle this.

**Comment by aaronpk** [comment]
I will need to enable CORS headers on the server for this to work.

**Comment by aaronpk** [comment]
This is added in 8c52d84c8e92ead7fa05846c7b866b944cd6cac7 and I've deployed it to the server.

**Comment by aswathrao** [comment]
Thanks
