### ISSUE TITLE
Client ID Registration

### ISSUE THREAD

**Issue by ItsEricWoodward** [aaronpk/indielogin.com#19]
I'm very interested in using IndieLogin.com to control access to my site. But, while I was trying to make it work, I received the following error: 

+ This client_id is not registered

I didn't see any instructions on the IndieLogin site indicating how to register for a client_id., so I thought I would open an issue on it.

Thanks for your time.

**Comment by aaronpk** [comment]
Thank you! I apologize for the lack of information here. Currently registering new client IDs is a manual process. I've gone ahead and added `https://itsericwoodward.com/` as a registered client ID so you should be able to use it now! Make sure to use the full URL as the client_id parameter.

**Comment by ItsEricWoodward** [comment]
Thanks, Aaron. I appreciate your help.

I saw that you opened #20 , so if you want to close this, feel free.
