### ISSUE TITLE
Auth fails if the url used for login is not the auth-provider

### ISSUE THREAD

**Issue by Aranad** [aaronpk/indielogin.com#23]
I have a number of sites linked into a group with bidirectional _rel="me"_ links which you can see at [organicdesign.pub/@aran](https://organicdesign.pub/@aran). The IndieAuth provider is [organicdesign.nz](https://organicdesign.nz).

If I go to [indielogin.com](https://indielogin.com) and login with [organicdesign.nz](https://organicdesign.nz) it's successful, but using [organicdesign.pub/@aran](https://organicdesign.pub/@aran) fails saying that none of the _rel="me"_ links found on the site are recognised as supported providers, even though organicdesign.nz is in that list and known to work.

**Comment by aaronpk** [comment]
In your example, `https://organicdesign.nz/` is a valid IndieAuth profile URL and is correctly set up to tell apps where to go to authenticate you, `https://organicdesign.nz/auth/`. It's incorrect to say that `https://organicdesign.nz/` is an IndieAuth _provider_, but it is an IndieAuth profile URL instead.

You need to add the `<link rel="authorization_endpoint" href="https://organicdesign.nz/auth/">` to your profile URL at `https://organicdesign.pub/@aran` and then indielogin.com will pick it up and redirect to that to authenticate you.

The way this works is the URL you type in, `https://organicdesign.pub/@aran` is considered your identity URL, and needs to tell indielogin.com where to authenticate you. indielogin.com only uses rel=me links for email and twitter/github profiles.

**Comment by Aranad** [comment]
Ah ok cool thanks a lot for the clear explanation :-) I had the concept a bit wrong, I was thinking that it would find which one of the urls in the rel=me group had the IndieAuth link and use that.
