### ISSUE TITLE
Could we simply use an auth service directly?

### ISSUE THREAD

**Issue by fluffy-critter** [aaronpk/indielogin.com#24]
It would be nice to reduce the barrier to entry by allowing people to log in using the identity from the service itself, rather than needing to set up a profile page with the correct `rel="me"` stuff. For example, if I could log in *as* `https://twitter.com/fluffy` or `https://github.com/fluffy-critter` (for bonus points, allowing the `http://` form as well).

It would also be nice to have a wider net on the supported OAuth providers, for example supporting any Mastodon service out of the box. Maybe supporting OpenID while we're at it, so people can use e.g. Dreamwidth.

The context for this is I am intending to build private entry support into my CMS, and would love for my less-tech-savvy friends to be able to authenticate using existing services. I wrote up some [kind-of scattered thoughts about it](http://publ.beesbuzz.biz/blog/392-v0-3-11).

**Comment by jalcine** [comment]
On Saturday, 15 December 2018 01:20:32 PST fluffy wrote:
> It would be nice to reduce the barrier to entry by allowing people to log in
> using the identity from the service itself, rather than needing to set up a
> profile page with the correct `rel="me"` stuff. For example, if I could log
> in *as* `https://twitter.com/fluffy` or `https://github.com/fluffy-critter`
> (for bonus points, allowing the `http://` form as well).

indielogin.com will handle the case of users entering a insecure HTTP URI and 
"upgrading"/redirecting it to a HTTPS one; IIRC. It's been an issue mentioned 
before in here.

> It would also be nice to have a wider net on the supported OAuth providers,
> for example supporting any Mastodon service out of the box.

This is something I've wanted myself for some time now! Just requires a PR and 
some logic around it. The act of making an OAuth client via Mastodon via the 
API looks simple enough[1]; most mobile clients use this as the method of 
authorizing users. I'm using that approach for my native desktop Mastodon 
client too.

> The context for this is I am intending to build private entry support into
> my CMS, and would love for my less-tech-savvy friends to be able to
> authenticate using existing services. I wrote up some [kind-of scattered
> thoughts about it](http://publ.beesbuzz.biz/blog/392-v0-3-11).

Lots of content in that post - eager to read it soon!

[1]:  https://github.com/tootsuite/documentation/blob/master/Using-the-API/
API.md#apps

**Comment by aaronpk** [comment]
> When I authenticate as http://beesbuzz.biz it does not upgrade to https://beesbuzz.biz

You need to have a redirect from http://beesbuzz.biz/ to https://beesbuzz.biz/ if you want that to work. Right now your site is served from both URLs.

> But regardless of scheme upgrades I’d love to be able to auth as my twitter or github (or other provider) identity directly rather than requiring a profile page on my own domain or whatever

The goal of this service is not to be a generic OAuth wrapper around various silo services, the point is to have people log in with an identity URL they control.

> It would also be nice to have a wider net on the supported OAuth providers,
 for example supporting any Mastodon service out of the box.

If Mastodon added IndieAuth support, then any Mastodon URL would be able to be used as the identity URL when logging in to things that use this service. Since Mastodon is already an OAuth server, it's not a huge change to add IndieAuth support to it. That would be the best approach, since that would be the most flexible in the future.

**Comment by fluffy-critter** [comment]
Yeah, I realize that http and https are possibly separate sites with different access control and so on, I just wish there were a way that I could indicate that they are equivalent in this case (without automatically redirecting everyone to https, which is not as universally accessible as people assume).

> The goal of this service is not to be a generic OAuth wrapper around various silo services, the point is to have people log in with an identity URL they control.

That's fair from a long-term goal perspective, but it feels like a barrier to adoption. Wouldn't it be better to help people to transition away from silo services without having to go all-in?

> Since Mastodon is already an OAuth server, it's not a huge change to add IndieAuth support to it. That would be the best approach, since that would be the most flexible in the future.

Okay, I'll open a feature request with the Mastodon project. Thanks!

**Comment by fluffy-critter** [comment]
Added comment to close-enough issue, https://github.com/tootsuite/mastodon/issues/4800

**Comment by aaronpk** [comment]
After thinking about this some more, I still don't want to add direct silo login as a feature to this project. If you're interested in having people log in to your site with a twitter account, there are plenty of other services that you can use for that.

* https://developer.okta.com/docs/concepts/social-login/
* https://auth0.com/learn/social-login/
* https://oauth.io/

I'm going to close the issue as the other discussion here has been moved elsewhere already.
