### ISSUE TITLE
indielogin won't recognize any of my rel=me links on xam.dk

### ISSUE THREAD

**Issue by maxandersen** [aaronpk/indielogin.com#25]
I've added all the required links formats for twitter, github, etc. but I keep getting "We couldn't find any way to authenticate you using your website." when trying.

Any ways to figure out why it is failing ?

**Comment by jalcine** [comment]
> I've added all the required links formats for twitter, github, etc. but I keep getting "We couldn't find any way to authenticate you using your website." when trying.
> 
> Any ways to figure out why it is failing ?

What's your URI?

**Comment by jalcine** [comment]
![screenshot_20181224_200406](https://user-images.githubusercontent.com/452100/50411716-1a1c9080-07b7-11e9-8300-86c26c50259b.png)

Hmm, I see this screen when I try out https://xam.dk/ to https://indielogin.com.

**Comment by maxandersen** [comment]
works for me this morning too - could it be that webmention.io & co caches its read of sites ? I published a few times within 10-20 minutes and nothing seemed to take effect - until now a few hours laster ? 

in any case it works for me now - thanks!

**Comment by jalcine** [comment]
> works for me this morning too - could it be that webmention.io & co caches its read of sites ? I published a few times within 10-20 minutes and nothing seemed to take effect - until now a few hours laster ?
> 
> in any case it works for me now - thanks!

Very much so; hitting pages all of the time is a easy DoS vector.

**Comment by maxandersen** [comment]
Fully understood - it might be useful if the error page state the timestamp / expiration so one can know how long to wait before a recheck is possible.
