### ISSUE TITLE
Error 403 when using indielogin on my site

### ISSUE THREAD

**Issue by SGallay** [aaronpk/indielogin.com#26]
Hi! First, my apologies if this is not the right place to discuss user issues; I tried to find support forums, but this is the only place I found.

I've tried to implement indielogin on my web site https://alias.erdorin.org and everything seems to work properly, until the very last phase:

1. Go to https://indielogin.com/
2. Enter my blog address in the field
3. I then get to the screen "The app https://indielogin.com/ would like to sign you in as https://alias.erdorin.org/."
4. Click Authenticate
5. Get a Error 403 in return. "Can't access requested item. It's either protected or can't be read by the server." (translated from French)

Any idea about what is wrong? Or, if I'm in the wrong place, any suggestion of a support channel?

Many thanks in advance!

**Comment by aaronpk** [comment]
I'm assuming when you see the error 403 that is coming from your website? Is your website URL in the address bar when that error message is visible?

This sounds like a problem with either the [WordPress plugin](https://github.com/indieweb/wordpress-indieauth) or something configured in your hosting environment.

**Comment by SGallay** [comment]
Yes, my site's URL is in the URL in the address bar.

Should I bring the issue to Wordpress forums then?
