### ISSUE TITLE
New client id registration

### ISSUE THREAD

**Issue by szkiba** [aaronpk/indielogin.com#28]
As I see from other issues, client id registration is manual process currently.
Please register https://demo.phantauth.ga/indieauth as a client (it seem works fin on localhot, but I get client_id not registered error on this url).
The above URL is my staging url, the production one will be https://demo.phantauth.me/indieauth
This one currently not exists, but if it is not a problem, please register both.
Thanx
Iván

**Comment by aaronpk** [comment]
Sorry for the delay! These are both registered now.

**Comment by cweiske** [comment]
Relates to #20.
