### ISSUE TITLE
Missing Refresh link on provider selection screen that was there in indieauth version

### ISSUE THREAD

**Issue by aswathrao** [aaronpk/indielogin.com#29]
In indieauth version, in the popup where the user selects the auth provider, there is a Refresh link that the user can click to force indieauth to rescan is id page and refresh the list of providers. That is not available in indielogin version. Is this by design? Has it been replaced by an alternate scheme?

I had sent an email describing why this was useful for my use case and a suggestion on a preferred scheme.

Thanks
Aswath

**Comment by aaronpk** [comment]
This one doesn't cache the list of discovered providers, it's loaded new each time the user visits the page. If you don't see what you expect the first time you can just reload the page and it will fetch them again. I can add a reload button to make it obvious but really it will be the same as reloading the browser.

**Comment by aswathrao** [comment]
I am attaching a screenshot of the response I get. Refreshing the browser produces the same screen. To recap the scenario is I have logged into the site that is maintaining my ID URL. I am in the process of verifying one of the providers. The verification process is the temporarily change the ID to contain just this provider and authenticating the ID. That is when I get this screen. Instead I am expecting the usual verification screen listing just this provider.

If I click on "Log in as a different user" and then click on Continue in the following screen, I get the desired screen. My intention is to avoid the first two interactions.
![screenshot 2019-02-19 at 4 20 18 pm](https://user-images.githubusercontent.com/21302178/53048814-9ce26480-3463-11e9-95c4-826e970d1866.png)

**Comment by aaronpk** [comment]
Ok, that's something different. I added this "remember me" stage to indielogin.com to avoid the need to bounce out to providers if you've already logged in on indielogin.com before. The idea with a provider is that it's a way to prove that you control the identity URL, but once you do that one time there isn't a need to go out to that provider again, so let's skip it entirely, saves time all around.

The "log in as a different user" bascially forgets this "remember me" step and starts from scratch.

I am unclear on why you are trying to verify a specific provider? Is that just for debugging or is this some part of your normal expected flow?

**Comment by aswathrao** [comment]
It is a proper flow though it will be invoked only occasionally. The app is aimed to be self-hosted by normal user. So it is designed to be "minimal touch". Since many users may not have an ID URL, the app hosts profiles of the users and use it as their ID URL. The app does not manage password and we bootstrap the ID URL using the user's email id. Since the user may not want to publicly share their email id, we have a procedure whereby they can add additional providers. We need to ensure that at least one provider is verified to be working correctly. To this end we have a mechanism for the user to request verification of a provider. In this routine, we need this "forget me" routine so we could temporarily present a single provider to indielogin.

As I indicated it my email id, it will be nice if the RP can specify an optional parameter requesting "forget me" routine.

**Comment by aaronpk** [comment]
Ok that's interesting. Is there a reason you don't want to make this app a real IndieAuth provider? That would mean users would never even see a prompt on indielogin.com, and indielogin.com and sites using indielogin.com would only ever see the user's ID URL. It does mean that this app would be responsible for authenticating users, but it kind of sounds like you're doing a lot of that work already?

I guess I'm unclear on your original reasons for using indielogin.com. The goal with indielogin.com is that it's used by apps like the indieweb wiki to get users to log in, where it would be too much work to implement all that code in the wiki itself.

**Comment by aswathrao** [comment]
I am not sure whether I gave you the wrong impression that the app is directly authenticating users. It depends on indielogin. (It used to depend on OpenID, but that kind of disappeared.) I may be mistaken, but I am anticipating that the app is bundled with an instance of indieauth, then shouldn't it get permission from Twitter and Github. I do not want to add this additional admin function to the common users.

I am using indieauth for the same reason that you are suggesting. There is no need for password administration; user can easily migrate from one server to another, especially if the ID URL is not derived from the app server (bring your own ID URL). I am not sure whether I answered your questions.If not let me know. I will try.

**Comment by aaronpk** [comment]
I just launched a change that adds a parameter `prompt=login` into the initial request. That should hopefully do what you are looking for!

**Comment by aswathrao** [comment]
Aaron:

Thanks for adding the new parameter. But it is not working as I expected.
Probably we are making an error in invoking this optional parameter. We
added the following to the Submit procedure: <input type="hidden"
name="prompt" value="login" />. With this addition, we are still getting
the popup page saying logged in as ..., instead of asking for verification.
So we assumed that this is not the correct format and used <input
type="hidden" name="prompt=login" />. This also did not work. Can you
please let us know what is the correct format of invocation?

Thanks a lot.
Aswath
