### ISSUE TITLE
successful login not actually successful

### ISSUE THREAD

**Issue by raynamharris** [aaronpk/indielogin.com#30]
When using indilogin, I get a nice contratulations message, but then I am not actually logged in an therefore can edit any content on https://indieweb.org/. @gRegorLove thinks it might be related to the fact that I don't have a personalized url....

![screen shot 2019-02-23 at 3 29 07 pm](https://user-images.githubusercontent.com/7544197/53291889-df67b200-377f-11e9-86e9-001a0aec2b07.png)

**Comment by raynamharris** [comment]
I'm using https://raynamharris.github.io/ which is authenticated via GitHub and twitter

**Comment by Zegnat** [comment]
I am afraid @gRegorLove is right. You have correctly setup IndieAuth on that URL, so indielogin.com lets you authenticate. But the IndieWeb wiki [disallows a number of domains, including github.io](https://github.com/indieweb/mediawiki-extensions/blob/196b02b6c688b1a026b51f3c80d4e912304899b8/LassoAuth.php#L17-L27).

**Comment by raynamharris** [comment]
Right! I fixed the problem by creating a custom domain :) Thanks for all your help at IndieWebCamp Austin!

**Comment by filips123** [comment]
@Zegnat Why are that domains on blacklist.

**Comment by Zegnat** [comment]
@filips123, I am honestly not sure where the list originated from. I guess the idea is that recommending people to own their identity is hard to consolidate with getting people running on subdomains owned by silos.

They are probably up for debate, I just wanted to point out it is a specific choice by the wiki and has nothing to do with indielogin.com itself! The login system doesn’t care.

**Comment by filips123** [comment]
@Zegnat Would it be possible to remove some domains from the list. This is because some of providers that are blocked only allow custom domain if user additionally pay for bigger plan. And many users don't have their own domains.

**Comment by Zegnat** [comment]
> Would it be possible to remove some domains from the list.

Maybe? Like I said, the blocklist is probably up for debate, I just don’t actually remember the policy for it. Sounds like something you could flag as an issue on [the indieweb/wiki repository](https://github.com/indieweb/wiki/issues/) or [discuss in the meta channel](https://indieweb.org/discuss).
