### ISSUE TITLE
please change client_id registration

### ISSUE THREAD

**Issue by szkiba** [aaronpk/indielogin.com#31]
I have 2 client_id registered
https://demo.phantauth.ga/indieauth
https://demo.phantauth.me/indieauth

please change these to
https://www.phantauth.ga/test/indieauth
https://www.phantauth.me/test/indieauth

and also please add
https://www.phantauth.net/test/indieauth

thank you
BR
Ivan

**Comment by aaronpk** [comment]
These have been updated.

**Comment by cweiske** [comment]
Relates to #20.
