### ISSUE TITLE
Email not received

### ISSUE THREAD

**Issue by filips123** [aaronpk/indielogin.com#32]
Emails with one-time code are not received when using login with email.

**Comment by iamwebrocker** [comment]
+1

**Comment by aaronpk** [comment]
Check your spam folder. I've tried to do all the right DKIM/SPF stuff to get the emails delivered, but some providers are still marking them as spam.

**Comment by iamwebrocker** [comment]
Hi Aaron, thx for looking/taking the time here :-)
there's nothing in the spam folder, but I suspect that my provider already does some filtering at the mailserver level, before "my" account level settings and then local settings will be applied. Had "fun" with SPF related bounces just recently.

**Comment by jlelse** [comment]
On my server the mail get's rejected: `Sender address rejected: Domain not found`

So it seems like the Mailgun setup isn't correct. There is no domain record for mail.indielogin.com.

**Comment by jlelse** [comment]
@aaronpk Could you please just add this one DNS entry? 🙈 I think the Mailgun docs tell what to point it to.

**Comment by aaronpk** [comment]
I don't see anything in the Mailgun docs about this, and Mailgun says all the necessary DNS is added. But now that you mention, it I think I've hit this issue before with other domains. It looks like some mail servers do an `A/CNAME` record lookup on the domain, even though that absolutely isn't required for email to be delivered.

In any case, I've added this DNS record so hopefully this should go away soon.

**Comment by iamwebrocker** [comment]
Hi Aaron,

thank you, it now works for me - received the email, all good now. 👍

**Comment by filips123** [comment]
@aaronpk It also works for me. However, email often goes to spam. Can you also fix this?

Also, is it secure to only use 4-char code? Couldn't this be brute-forced in only a few seconds?

**Comment by aaronpk** [comment]
I'm going to close the issue since it sounds like the original problem has been resolved. Thanks for helping me track it down!

**Comment by filips123** [comment]
> I don't really have any control over whether they end up in spam other than doing these fixes like adding DNS entries and DKIM/SPF records and such.

Can you also try to add that DNS entries?

> the 4 digit code requires entering it in the same browser that initiated the request, so it can't be brute forced really.

What if the attacker enters site URL, chooses to log in with the email and then tries all possible combinations in the same session?

**Comment by aaronpk** [comment]
That DNS entry is the one brought up here. I don't know of any other anti-spam techniques now.

Let's discuss the brute force issue in a [separate thread](https://github.com/aaronpk/indielogin.com/issues/39).
