### ISSUE TITLE
Failing to sign in with WordPress-based website and IndieWeb WordPress plugins

### ISSUE THREAD

**Issue by BjoernKW** [aaronpk/indielogin.com#35]
Trying to sign in with my website (WordPress-based, IndieWeb plugins installed) under https://indielogin.com/auth results in a "We couldn't find any way to authenticate you using your website." message.

I followed the instructions after installing the WordPress plugins.

This is the website in question: https://bjoernkw.com

**Comment by Zegnat** [comment]
Is this still an issue? Entering your website in the test form on [the indielogin homepage](https://indielogin.com/) gets me to the next step where I can choose to authenticate with GitHub, Twitter, or Keybase. That seems right.

**Comment by BjoernKW** [comment]
Yes, it works now. Thank you!
