### ISSUE TITLE
trouble logging in though it worked previously

### ISSUE THREAD

**Issue by joejenett** [aaronpk/indielogin.com#36]
When trying to login using simply.micro.jenett.org, I get the following error message:

Client error: `GET https://simply.micro.jenett.org/` resulted in a `406 Not Acceptable` response:
<html><head><title>Error 406 - Not Acceptable</title><head><body><h1>Error 406 - Not Acceptable</h1><p>Generally a 406 e (truncated...)

My browser settings allow all cookies from indieweb.org and indielogin.com and I have the IndieAuth plugin installed. There's also a <link rel="me" type link for my email address in the site's pages and my h-card is also present.

I get a similar message trying from simply.personal.jenett.org and jenett.org (not a blog, so no IndieAuth, but proper rel="me" links in the page)

**Comment by aaronpk** [comment]
This error is from your web server. Your web server is refusing to respond to the request that indielogin.com makes to fetch your home page. Does your server require any particular HTTP headers? Indielogin.com doesn't send much, and doesn't try to pretend it's a browser. What HTTP server are you using?

**Comment by joejenett** [comment]
My hosting provider is running Apache 2.4.39 on linux if that's what you're asking. Seeing what I can find about the headers...

**Comment by aaronpk** [comment]
Are they running any kind of bot protection or "mod_security" or anything?

**Comment by joejenett** [comment]
I have a choice to disable mod_security altogether or disable only certain rules related to the error so I think the best thing to do is for me to work on resolving it and letting you know when and how it gets resolved.

A year or so ago I encountered a similar problem and it turned out to be due to including "http://" or "https://" in the login form. That problem was resolved by simply putting the domain name in the form without the "http" prefix. This time around, I tried both ways and still got the error. I'm assuming that the form now should accept submitting it either way. Also tried with and without the tailing /. If these these make a difference, please let me know.

**Comment by joejenett** [comment]
It looks like cPanel will not let me disable mod security - which appears to be my only choice and which I don't want to do anyway. But I am able to whitelist indielogin.com's IP (104.237.158.110) which I did. It gave a message that the server cannot be restarted so I'll  put a call in about that. No need to do anything on your part until you hear from me. I'll also share with them the info in the "406" document you linked to above and see what they might be able to do regarding negotiation headers, etc. Thanks Aaron.

**Comment by joejenett** [comment]
What I found out is that they're looking for the user-agent header - that's what's causing the 406 error

**Comment by joejenett** [comment]
Here's a copy of relevant info from the chat with them:
09:41:09 PM [Joe Jenett] Okay - to confirm, you're saying if it's whitelisted but they're not including a user-agent header that mod security will block their request and generate a 406 error --- right?
09:41:41 PM [Ronnie H.] Yep! Even with the whitelist, you need that header.

Will await your response at your convenience Aaron.

**Comment by Zegnat** [comment]
I noticed [the default user agent is an empty string](https://github.com/aaronpk/indielogin.com/blob/f1c4a7abba894b097f4aeaafbba5287a2dfb9e30/lib/config.template.php#L5). Is this the same config you are using, @aaronpk?

**Comment by aaronpk** [comment]
I did a little investigation, and indielogin.com wasn't using the config user-agent option for this profile request. It was instead sending the default user agent: `GuzzleHttp/6.3.3 curl/7.54.0 PHP/7.2.6`. I'm guessing mod_security was unhappy about the generic user agent and blocked the request. I've fix it to include a better user agent string and it looks like it can fetch your profile now.

**Comment by joejenett** [comment]
tested 2 scenarios - one of which works:
1) Using jenett.org, which is a static page with rel="me" link for email but no indieauth endpoints defined said okay - using the code emailed to me resulted in: "our IndieAuth server did not return a valid state parameter." BUT

2) Using simply.micro.jenett.org, one of my WP blogs with both the email address and the IndieAuth plugin (with corresponding endpoints in the page source), now works perfectly.

Conclusion - The process appears to depend on IndieAuth which is fine in my case as long as I don't try to login with just jenett.org. For my purposes, please consider this resolved. And thanks for what you did to resolve it! We're good.

**Comment by aaronpk** [comment]
Great! 

That's a strange error to get from the other site, but I'll look into that separately.
