### ISSUE TITLE
Invalid state error with email authentication

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/indielogin.com#37]
I've heard reports of people getting an "invalid state" error after using email authentication. I haven't been able to reproduce this myself, but I'm going to leave this issue open in case others encounter it. Please note below if this has happened to you.

**Comment by Ryuno-Ki** [comment]
I don't get any email (what would be the sender?).

But logging in with GitHub yields invalid state.
Twitter works, so I use that for now...

**Comment by aaronpk** [comment]
@Ryuno-Ki Are you using any sort of browser plugins that might be interfering with cookies? Things like ad blockers? Also what browser are you using?
