### ISSUE TITLE
Prevent brute-forcing the email code

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/indielogin.com#39]
It is theoretically possible for someone to attempt to authenticate via email, then try all 10,000 4-digit codes until one works. There should be some sort of rate limiting feature to prevent this.

**Comment by aaronpk** [comment]
Minor correction, I forgot that it uses letters as well as numbers to generate the code, so there are a lot more than 10,000 possible codes.

The character set is `23456789ABCDEFGHJKLMNPQRSTUVWXYZ` (ambiguous characters removed, case insensitive, leaving 32 chars), so that means the number of possible codes is 32^4 = 1,048,576.

The system gives you 5 minutes to enter a valid code, so this would require 3495 requests per second in order to try all possible codes.

**Comment by filips123** [comment]
I didn't know that code can also contain letters and numbers. Now website probably even won't be able to handle so many requests 😃

But still, there should be some limit to prevent possible attacks even more. There could be a limit of 60 incorrect attempts per hour. It is hard to submit incorrect code 60-times in one hour if you are real user, but easy to do this is you are a bot.

**Comment by aaronpk** [comment]
Ok, I just pushed a change that will allow only 4 failed attempts to enter a code in a given session. Unless I'm thinking about this entirely wrong, this should make a brute force attempt virtually impossible since you'd have 4/1048576 chance of guessing the code at any given time.

**Comment by filips123** [comment]
This is good.

But what if attacker just submits same code (maybe `AAAA`) more than 1048576-times? There will be no other possible options so there is a chance that target code will be returned again. Or the attacker can get very lucky and finds the code in the first try...

Even if that's pretty impossible, it could maybe still be good to add the additional time-based block.

**Comment by aaronpk** [comment]
I don't want to implement something that can be used as a denial of service attack against the user, so I'm not particularly interested in implementing a global time-based block. Limiting to an IP address won't really help either because it's too easy to set up bot farms now.

> But what if attacker just submits same code (maybe AAAA) more than 1048576-times?

Doesn't matter, because the code expires after 4 wrong guesses. You get a 4-letter code assigned, and have 4 attempts to enter the correct code. The attacker has a 4/1048576 chance of getting it right on each of the 4 attempts. After that, the code expires and they need to request a new one. The attacker could of course do this, resetting their chances again. There is no way to exhaust all possibilities, this just hard-codes the odds of a brute force attack to 4/1048576.

I could decrease the odds to 1/a billion by adding two more letters, making it a 6-letter code.

**Comment by filips123** [comment]
Then it is good. Maybe you can make a 6-letter code to be sure.

**Comment by aaronpk** [comment]
Codes are now 6 letters.
