### ISSUE TITLE
Cannot click VERIFY with qutebrowser with PGP Auth

### ISSUE THREAD

**Issue by gnusupport** [aaronpk/indielogin.com#41]
I am trying to click VERIFY but does not work. Using PGP Auth with https://gnu.support

**Comment by aaronpk** [comment]
The website will wait until it sees what it expects a PGP signature to look like before enabling the Verify button. Can you provide a sample of a signed challenge from your PGP client? I thought I caught the most common ascii-armored formats but I could have missed some.

**Comment by lucible** [comment]
Perhaps you could add a note below or above the input saying that it requires a valid PGP signature before the button will be enabled? I was making a mistake in copying my signature without knowing it, and thought the button was broken until I read this issue and realized I'd been copying the signed challenge wrong!

**Comment by aaronpk** [comment]
Good idea, thanks. I've added a note there.
