### ISSUE TITLE
Login does not work with my website

### ISSUE THREAD

**Issue by MoritzGiessmann** [aaronpk/indielogin.com#53]
Hi! First of all, I really like the work you’re doing here!

I tried to use indielogin with my website https://moritzgiessmann.de/ following the tutorial, but it somehow doesn’t work and providing several rel=“me” links. I always get “None of the rel=me URLs found on your page were recognized as a supported provider“ and I am not able to identify the missing piece. 

It’d be nice if someone could take a look at what I’m missing.

Thanks a lot!

**Comment by aaronpk** [comment]
Try removing the slash from your twitter and GitHub URLs, those are the only two of yours that would be supported

**Comment by MoritzGiessmann** [comment]
Thanks! It worked!
