### ISSUE TITLE
Plans to implement RFC 5988 / HTTP Link Header?

### ISSUE THREAD

**Issue by mro** [aaronpk/indielogin.com#60]
a necessity for non-HTML web.

Like e.g. foaf Documents. (With XSLT they make IMHO excellent personal pages. Like https://mro.name/~me. Very lean tooling.)

**Comment by mro** [comment]
maybe related to https://github.com/indieweb/indiewebify-me/issues/78

**Comment by aaronpk** [comment]
No plans for now. Also it looks like that page is 404 now anyway.
