### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by rebelchris** [aaronpk/indielogin.com#65]
Hey guys,

I've been authenticated with indielogin for a couple of days, but today getting the following error.

<img width="687" alt="Screenshot 2020-09-15 at 12 50 45" src="https://user-images.githubusercontent.com/554874/93201922-29452e00-f752-11ea-89f1-09731e4ef1c4.png">

The error reads as follows:

`cURL error 28: Operation timed out after 10001 milliseconds with 0 out of 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

**Comment by aaronpk** [comment]
Looks like the server is able to fetch your website again. Not sure what was wrong.
