### ISSUE TITLE
ca certificates

### ISSUE THREAD

**Issue by sebbu2** [aaronpk/indielogin.com#68]
While investigating the cause of my previous issue (#67), I found out it's probably caused by outdated (or missing) ca certificates.

I was able to get a ssl error when trying locally
`<?php
$ch=curl_init('https://sebbu.fr/');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$data=curl_exec($ch);
var_dump(curl_errno($ch),curl_error($ch),$data);
?>`

Which got fixed by adding
`curl.cainfo = 'D:/php/cacert.pem'
openssl.cafile = 'D:/php/cacert.pem'`
to the php.ini, or
`curl_setopt($ch, CURLOPT_CAINFO, $cert);`
to the file, with $cert being the locally saved [cacert.pem](https://curl.haxx.se/ca/cacert.pem)

**Comment by aaronpk** [comment]
I can't seem to replicate this anymore, it looks like it has no trouble fetching content from this website. If you changed your cert or config do you happen to know what it was previously so I can try to replicate?

**Comment by sebbu2** [comment]
I haven't changed my cert or config. I was only able to reproduce it with curl, not with fopen or file_get_contents.
Of course, disabling verification made it work too, not just adding the certificates.

**Comment by aaronpk** [comment]
Are you still unable to log in? I did push a fix to surface the curl errors now but as far as I can tell it isn't having trouble with the cert on your site.

**Comment by sebbu2** [comment]
I'm still unable, but for a different reason, i got 307 / max redirects (8) now... which shouldn't happen, as both indieauth.com (the website / auth) and indieauth-client-php works

**Comment by aaronpk** [comment]
The server has no trouble fetching your site now so I'm going to close this. Feel free to reopen a new issue if you're still seeing the too many redirects error.
