### ISSUE TITLE
Can't login on clawfire.net using twitter

### ISSUE THREAD

**Issue by clawfire** [aaronpk/indielogin.com#71]
![Capture d’écran 2021-01-01 à 21 54 06](https://user-images.githubusercontent.com/1178/103446083-e0bb6d00-4c7b-11eb-829b-2f27a671a9c6.png)

**Comment by jalcine** [comment]
Do you mind linking to your Twitter profile? Your site doesn't seem to highlight any reference to it (or _any_ Microformats for that matter) https://xray.p3k.app/parse?url=https%3A%2F%2Fthibaultmilan.com%2F&pretty=true

**Comment by clawfire** [comment]
Well it’s for clawfire.net (as you can see) and my twitter handle is @clawfire

**Comment by jalcine** [comment]
I'd recommend reading over https://indielogin.com/setup (namely https://indielogin.com/setup#twitter) to make sure your site's ready for IndieAuth.

**Comment by clawfire** [comment]
Well I did. And my link is just right here.

![Capture d’écran 2021-01-01 à 22 46 21](https://user-images.githubusercontent.com/1178/103446737-4bbc7200-4c83-11eb-90c8-5efd52e640c8.png)

**Comment by Ryuno-Ki** [comment]
Hm, my [structured data parser extension](https://addons.mozilla.org/en-GB/firefox/addon/openlink-structured-data-sniff/) cannot detect it, although the markup looks valid :eyes: 
(On a side note, you should [add additional rel attributes to secure your site](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/) for `target="_blank"` links).

**Comment by clawfire** [comment]
Thanks for the link about the `target=_"blank"` security issues. I wasn't aware of it. I'll have a good amount of work on that template 😁

**Comment by Zegnat** [comment]
Wonder if there was some temporary hick-up in the indielogin.com cache or something else.

If I go to login using `https://clawfire.net/` it correctly shows a Twitter button. I am then able to click it and authorize the app for Twitter access. Of course I end up on a screen telling me that I am "logged in to Twitter as @martijnvdven but your website links to @clawfire", which is exactly the error I would expect as I am not allowed to identify as clawfire.net.

But I assume if I were logged in with the correct Twitter account, it would have worked. Are you still getting errors, @clawfire? If yes, which steps are you able to take in the flow before an error comes up?

**Comment by clawfire** [comment]
I'm going to login using https://clawfire.net, it correctly shows a Twitter button (as well as GitHub & email). I am able to click it and authorize the app for Twitter access. Then I'm going back to indielogin and have the following error message

> Your Twitter profile linked to https://clawfire.net/ but we were expecting to see https://clawfire.net/. Make sure you link to https://clawfire.net/ in your Twitter profile.

**Comment by Zegnat** [comment]
Super weird, I see no obvious problems with your setup, but not with the code either. Hopefully @aaronpk will be able to see something in the logs, [I think it logs](https://github.com/aaronpk/indielogin.com/blob/606963a3e8c3b9fcab2786f487733c5118a63643/app/Provider/Twitter.php#L106) the values it tries to match on.

**Comment by aaronpk** [comment]
I found some inconsistencies which I believe were the reason for the kind of strange error message at the top of this thread. I just changed things around, so try again and let me know if it works now. I'm thinking the original cause of this was because you entered `http://clawfire.net` rather than `https://clawfire.net` but that shouldn't matter anymore, it should be able to handle that now.

**Comment by clawfire** [comment]
Hey It works 😃 
Thanks !
