### ISSUE TITLE
Problem signing in using PGP key

### ISSUE THREAD

**Issue by jonboc** [aaronpk/indielogin.com#76]
My site has the following code in the home page:

`<a href="/key.txt" rel="pgpkey authn">PGP Key</a>`

key.txt contains my public key. However when I sign the challenge with the matching private key I get the following error:

**There was a problem! The signature was valid, but was signed with a different key than we expected.**

I'm not sure what I am doing wrong.

**Comment by kimonoki** [comment]
Maybe you can check if you had also encrypted? It's possible to encrypt and sign at the same time

**Comment by aaronpk** [comment]
Sorry, I'm having trouble getting things working with PGP keys so I'm just disabling it entirely for now.
