### ISSUE TITLE
Authenticating by Email - only needed for initial registration?

### ISSUE THREAD

**Issue by tunetheweb** [aaronpk/indielogin.com#79]
If authenticating by email is it necessary to keep the `<a href="mailto:me@example.com" rel="me">me@example.com</a>` on the website after registration? Or can we remove it after registration? Or is it rechecked for each authentication?

Just trying to avoid spam bots picking up the email by leaving it in the HTML source.

**Comment by aaronpk** [comment]
There is no "account" at indielogin.com, you have to authenticate via one of the methods each time you log in to a site. If you want to use the email method it will need to be present there all the time. One solution is to use an email address specifically for indielogin.com, and then reject all emails to that address unless they come from indielogin.com
