### ISSUE TITLE
PGP works in indieauth but not in indielogin

### ISSUE THREAD

**Issue by aswathrao** [aaronpk/indielogin.com#8]
When I try PGP key in indieauth w http://aswath.mocaedu.com/aswath1.html, it works as expected. But PGP Key option does not appear in indielogin. Is it an error my part or something else? Appreciate your help. Thanks.

**Comment by aaronpk** [comment]
Looks like I accidentally made it require the `authn` rel value on the PGP key too. I'll update that to find just the `rel=pgpkey` value as well.

**Comment by aswathrao** [comment]
Thank you

**Comment by aaronpk** [comment]
Pushed a change! Try it now!

**Comment by aswathrao** [comment]
Tried and works fine. Thanks again.
