### ISSUE TITLE
IndieLogin does not imply http(s) when verifying GitHub profiles 

### ISSUE THREAD

**Issue by Craftplacer** [aaronpk/indielogin.com#84]
When using the domain name alone on the GitHub profile, IndieLogin fails authenticating because it expects a full URL. This behavior is probably unwanted because GitHub also implies https when only using the domain on the profile.

IndieLogin returns an error message like:
> Your GitHub profile linked to **domain** but we were expecting to see **https://domain/**. Make sure you link to **https://domain/** in your GitHub profile.

~~Furthermore it wasn't obvious at first that you had to link your site in your GitHub profile, because the setup instructions only detailed adding an `<a>` or `<link>`.~~

**Comment by aaronpk** [comment]
Just to clarify, do you mean in your GitHub account you had just the domain typed like this? 

<img width="340" alt="image" src="https://user-images.githubusercontent.com/113001/162828233-d9e9a1fd-2e87-4a02-a9f3-6cac2c6325cc.png">

Also what instructions did you find that didn't mention the GitHub profile needs to have the link? The instructions here mention it: https://indielogin.com/setup#github

**Comment by Craftplacer** [comment]
> Just to clarify, do you mean in your GitHub account you had just the domain typed like this?

Yup.

> Also what instructions did you find that didn't mention the GitHub profile needs to have the link? The instructions here mention it: https://indielogin.com/setup#github

My bad, I flew over the instructions looking for code rather than text.

**Comment by aaronpk** [comment]
Thanks, that's helpful! I have seen this error before and wasn't sure what was causing it! I'll update this to handle that case!
