### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by stelzch** [aaronpk/indielogin.com#90]
I can't seem to login with [my webpage](https://ch-st.de).
Even though I added a rel-me-link to my GitHub profile, the site just keeps reporting:

> We couldn't find any way to authenticate you using your website.

Any help would be greatly appreciated.

**Comment by lukasmalkmus** [comment]
<img width="635" alt="Screenshot 2022-11-14 at 11 31 01" src="https://user-images.githubusercontent.com/9931588/201638860-a68aec3f-2014-4172-bb8e-d9b3b74a31dd.png">

Looks good to me, no?

Can this be closed or are you still having issues?

**Comment by stelzch** [comment]
Yes, it magically seems to work now :)
Maybe some sort of caching issue?
Thanks!

**Comment by lukasmalkmus** [comment]
Maybe the links were not present on your root path? E.g. the links were present on `/about` but not `/`?

**Comment by stelzch** [comment]
IIRC I did not change anything on my site, but it just started working. I went through a few variations, however (rel-me on Github link, rel-me in `<meta>`, …)
