### ISSUE TITLE
Sending one-time code to mail seems not to work

### ISSUE THREAD

**Issue by schneyra** [aaronpk/indielogin.com#91]
Hey! I'm trying to log in with my website https://martinschneider.me

Oddly, I have just the option to use e-mail to login although I provide several links to profiles like github. 
Login via mail does not work for me. I'm not receiving an e-mail with a code.

**Comment by aaronpk** [comment]
Sorry, not sure what the problem is, but sometimes these emails go to spam or are just rejected by a mail server. I'm not seeing an abnormal number of failures in the logs. But that's why there are a bunch of other options to log in.
