### ISSUE TITLE
Signing with a Keybase key does not allow clicking the Verify button

### ISSUE THREAD

**Issue by catgirlinspace** [aaronpk/indielogin.com#93]
Attempting to authenticate to indielogin.com using a PGP key signed through the Keybase UI does not allow clicking the Verify button. Additionally, even if the verify button is manually enabled through the DOM, indielogin.com fails at verifying still. 

Using the keybase cli with `keybase pgp sign -m '(challenge text)'` as shown on indieauth.com works as expected, but is inconvenient and does not work on mobile.

**Comment by aaronpk** [comment]
Sorry, I'm having trouble getting things working with PGP keys so I'm just disabling it entirely for now.
