### ISSUE TITLE
Changed domain from www to naked TLD, and changed username, and now can't login to indieweb.org

### ISSUE THREAD

**Issue by HammyHavoc** [aaronpk/indielogin.com#98]
Hi all,

I changed my domain from [www.hammyhavoc.com](url) to just [hammyhavoc.com](url), and changed my WordPress username from `hammy` to `me`, so that I could use `me@hammyhavoc.com` as my username for people to follow. However, now I can't login to [indieweb.org](url).

Can anyone help?

**Comment by aaronpk** [comment]
You should be able to log in with "hammyhavoc.com" now. It would be helpful to know what kind of error message you're seeing.

**Comment by HammyHavoc** [comment]
Whilst being able to login, I now unfortunately have two accounts on IndieWeb.

There's https://indieweb.org/Special:Contributions/Www.hammyhavoc.com, which has my contributions and info from earlier on, and there's now a new account of https://indieweb.org/Special:Contributions/Hammyhavoc.com

**Comment by aaronpk** [comment]
Yes, that's correct, there isn't really the concept of "accounts" on the wiki. I see you made [a user page](https://indieweb.org/User:Www.hammyhavoc.com), you can just use the wiki "move" feature to move the page to your new domain.

**Comment by HammyHavoc** [comment]
Ah, I see! :- )

Let me know if that looks as expected from your end: https://indieweb.org/wiki/index.php?title=User:Hammyhavoc.com&action=history

If so, feel free to close the Issue. Have a wonderful 2023.
